#pragma once

#include "ResponseObjects/AskForPublicKeyResponse.h"
#include "ResponseObjects/ChatroomsListResponse.h"
#include "ResponseObjects/ContactsActionResponseDirect.h"
#include "ResponseObjects/ContactsActionResponseServer.h"
#include "ResponseObjects/HeartbeatPongResponse.h"
#include "ResponseObjects/ListResponse.h"
#include "ResponseObjects/LoginResponse.h"
#include "ResponseObjects/MessageChangeStatusResponse.h"
#include "ResponseObjects/MessagesResponse.h"
#include "ResponseObjects/PendingMessagesResponse.h"
#include "ResponseObjects/SendMessageResponse.h"
#include "ResponseObjects/SendOwnPublicKeyResponse.h"
#include "ResponseObjects/UsersListResponse.h"
#include "ResponseObjects/RoomMessagesResponse.h"
#include "ResponseObjects/ContactsListResponse.h"
#include "ResponseObjects/SearchUsersResponse.h"
#include "ResponseObjects/LogoutResponse.h"

#include "ResponseHandler.h"
