#!/bin/sh

for SIZE in 32 48 64 128 256
do
	xdg-icon-resource install --novendor --context apps --size $SIZE /usr/share/blocksettle/icons/blocksettle_$SIZE.png blocksettle
	xdg-icon-resource install --novendor --context apps --size $SIZE /usr/share/blocksettle/icons/blocksettle_signer_$SIZE.png blocksettle_signer
done

update-desktop-database

exit 0
