#!/usr/bin/python

import os
import time
from subprocess import Popen, PIPE, check_output, call
import platform

def execAndWait(cli_str):
   print '    EXEC:', cli_str
   process = Popen(cli_str, shell=True)
   while process.poll() == None:
      time.sleep(0.01)

# Ubuntu 10.10+ has issues with the regular gconftool-2 commands
# for registering URL handlers.  Need a different solution, but 
# it's a permanent one.
perm_app_register = True


def createDesktopFile(toDir):
   toPath = os.path.join(toDir, 'blocksettle.desktop') 
   deskfile = open(toPath, 'w')
   deskfile.write('[Desktop Entry]\n')
   deskfile.write('Type=Application\n')
   deskfile.write('Name=BlockSettle')
   deskfile.write('\n')
   deskfile.write('GenericName=BlockSettle Terminal\n')
   deskfile.write('Comment=BlockSettle real-time settlement network application and a wallet manager\n')
   deskfile.write('Categories=Qt;Network\n')
   deskfile.write('Exec=/usr/bin/blocksettle')
   if perm_app_register:
      deskfile.write(' %u')
   deskfile.write('\n')
   deskfile.write('Icon=blocksettle_icon\n')
   deskfile.write('StartupNotify=false\n')
   deskfile.write('Terminal=false\n')
   deskfile.close()


# Give the system time to actually get rid of the .desktop files
time.sleep(1)
createDesktopFile('.')

print '   Setting up menu items.'
execAndWait('xdg-icon-resource install --novendor --context apps --size 64 /usr/share/blocksettle/blocksettle.png blocksettle_icon')

execAndWait('desktop-file-install ./blocksettle.desktop')

if os.path.exists('/usr/share/desktop-directories'):
   execAndWait('xdg-desktop-menu install --novendor /usr/share/applications/blocksettle.desktop')

try:
   settings = check_output(['gsettings', 'get', 'com.canonical.Unity.Launcher', 'favorites'])
   settings = settings.replace(']', ', \'application://blocksettle.desktop\']')
   user = check_output(['cat', 'user']).rstrip()
   if user:
      call(['su', user, '-c', 'gsettings set com.canonical.Unity.Launcher favorites "' + settings + '"'])
except:
   print 'Failed to add app icon to Unity Launcher'

print ''
print '!!! BlockSettle Terminal installed successfully !!!'
print ''
print '  It can be removed at any time, either through your package '
print '  manager, or through the following command:'
print '      sudo dpkg -r bsterminal'
