#!/bin/bash

# Do not use this flag as it causes problems uninstalling if xdg-utils is missing
#set -e

if [ -d /usr/share/desktop-directories ] ; then
   xdg-desktop-menu  uninstall /usr/share/applications/blocksettle.desktop
fi

xdg-icon-resource uninstall --size 64 blocksettle_icon

rm -f /usr/share/applications/blocksettle.desktop
