#!/bin/sh

xdg-icon-resource install --novendor --context apps --size 64 /usr/share/blocksettle/blocksettle.png blocksettle
xdg-icon-resource install --novendor --context apps --size 64 /usr/share/blocksettle/blocksettle_signer.png blocksettle_signer

update-desktop-database
